---
- name: Query DNS resolve
  hosts: all
  serial: 0
#  remote_user: adm_onlanta
#  become: true
#  become_method: sudo

  tasks:

    - name: Curl repo result
      command: curl http://10.140.160.218/centos/
      register: repo

    - debug:
        msg: "{{ repo.stdout | regex_search('(.*(6-extras).*)') }}"
