---
- name: Query DNS resolve
  hosts: all
  serial: 0
#  remote_user: adm_onlanta
#  become: true
#  become_method: sudo

  tasks:

    - name: Register nslookup repo result
      command: getent hosts repo
      register: ns

    - debug:
        msg: "{{ ns.stdout | regex_search('(\\d+\\.\\d+\\.\\d+\\.\\d+)') }}"
