---
- name: Set NTP servers
  hosts: all
  serial: 0
#  remote_user: adm_onlanta
#  become: true
#  become_method: sudo

  tasks:

    - name: Set timezone to Europe/Moscow
      timezone:
        name: Europe/Moscow

